// [
//   {
//     "id": 1,
//     "name": "Beef Burger Premium",
//     "category": "fastfood",
//     "description": "Beef patty with fresh lettuce, tomato, and cheese in a soft sesame bun.",
//     "image_url": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
//     "price": 35000,
//     "rating": 4.7,
//     "shop_name": "Burger Bros",
//     "is_promos": true,
//     "is_trending": true
//   },
//   {
//     "id": 2,
//     "name": "Vegan Green Salad",
//     "category": "vegan",
//     "description": "Fresh mixed greens, cherry tomatoes, cucumber, and vegan dressing.",
//     "image_url": "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 25000,
//     "rating": 4.4,
//     "shop_name": "Healthy Hub",
//     "is_promos": false,
//     "is_trending": true
//   },
//   {
//     "id": 3,
//     "name": "Red Velvet Cake Slice",
//     "category": "dessert",
//     "description": "Soft and moist red velvet cake with cream cheese frosting.",
//     "image_url": "https://images.unsplash.com/photo-1614707269211-474b2510b3ad?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 22000,
//     "rating": 4.9,
//     "shop_name": "Sweet Spot",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 4,
//     "name": "Fish and Chips",
//     "category": "western",
//     "description": "Classic battered fish served with crispy fries and tartar sauce.",
//     "image_url": "https://images.unsplash.com/photo-1697748836791-9ddf7e616ece?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZmlzaCUyMGFuZCUyMGNoaXBzfGVufDB8fDB8fHww",
//     "price": 40000,
//     "rating": 4.3,
//     "shop_name": "Western Delight",
//     "is_promos": true,
//     "is_trending": false
//   },
//   {
//     "id": 5,
//     "name": "Spicy Fried Chicken",
//     "category": "fastfood",
//     "description": "Crispy chicken pieces seasoned with a special spicy blend.",
//     "image_url": "https://plus.unsplash.com/premium_photo-1683139916670-38113db90cb9?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 28000,
//     "rating": 4.8,
//     "shop_name": "Chicken Master",
//     "is_promos": true,
//     "is_trending": true
//   },
//   {
//     "id": 6,
//     "name": "Vegan Buddha Bowl",
//     "category": "vegan",
//     "description": "Rice, edamame, veggies, and tofu in a wholesome vegan bowl.",
//     "image_url": "https://plus.unsplash.com/premium_photo-1664648005739-ce9a51e31952?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 32000,
//     "rating": 4.5,
//     "shop_name": "Green Eats",
//     "is_promos": false,
//     "is_trending": true
//   },
//   {
//     "id": 7,
//     "name": "Chocolate Lava Cake",
//     "category": "dessert",
//     "description": "Warm chocolate cake with a gooey melted chocolate center.",
//     "image_url": "https://images.unsplash.com/photo-1617305855058-336d24456869?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 24000,
//     "rating": 4.9,
//     "shop_name": "Sweet Spot",
//     "is_promos": false,
//     "is_trending": true
//   },
//   {
//     "id": 8,
//     "name": "Chicken Katsu Curry",
//     "category": "western",
//     "description": "Japanese-style crispy chicken with curry sauce and rice.",
//     "image_url": "https://images.unsplash.com/photo-1677743540715-d4fe04852225?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 38000,
//     "rating": 4.6,
//     "shop_name": "Tokyo Bites",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 9,
//     "name": "Classic Cheeseburger",
//     "category": "fastfood",
//     "description": "Juicy beef patty with cheddar, tomato, and house sauce.",
//     "image_url": "https://plus.unsplash.com/premium_photo-1694769318070-5fbe38d744c6?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 27000,
//     "rating": 4.2,
//     "shop_name": "Burger Bros",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 10,
//     "name": "Avocado Toast",
//     "category": "vegan",
//     "description": "Whole-grain toast topped with fresh smashed avocado and seeds.",
//     "image_url": "https://images.unsplash.com/photo-1704545229893-4f1bb5ef16a1?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 21000,
//     "rating": 4.3,
//     "shop_name": "Green Eats",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 11,
//     "name": "Blueberry Pancakes",
//     "category": "dessert",
//     "description": "Fluffy pancakes with fresh blueberries and maple syrup.",
//     "image_url": "https://plus.unsplash.com/premium_photo-1692193552660-233948b757a4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Ymx1YmVycnklMjBwYW5jYWtlc3xlbnwwfHwwfHx8MA%3D%3D",
//     "price": 23000,
//     "rating": 4.8,
//     "shop_name": "Pancake House",
//     "is_promos": false,
//     "is_trending": true
//   },
//   {
//     "id": 12,
//     "name": "Grilled Salmon Steak",
//     "category": "western",
//     "description": "Grilled salmon with lemon butter sauce, served with veggies.",
//     "image_url": "https://plus.unsplash.com/premium_photo-1695658518299-04b349ca9214?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 45000,
//     "rating": 4.9,
//     "shop_name": "Western Delight",
//     "is_promos": true,
//     "is_trending": false
//   },
//   {
//     "id": 13,
//     "name": "Chicken Shawarma Wrap",
//     "category": "fastfood",
//     "description": "Grilled chicken slices wrapped with veggies and garlic sauce.",
//     "image_url": "https://images.unsplash.com/photo-1734772591537-15ac1b3b3c04?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 26000,
//     "rating": 4.1,
//     "shop_name": "Middle Feast",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 14,
//     "name": "Vegan Sushi Platter",
//     "category": "vegan",
//     "description": "Assorted vegan sushi rolls with soy sauce and wasabi.",
//     "image_url": "https://images.unsplash.com/photo-1726824863833-e88146cf0a72?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 35000,
//     "rating": 4.7,
//     "shop_name": "Tokyo Bites",
//     "is_promos": true,
//     "is_trending": true
//   },
//   {
//     "id": 15,
//     "name": "Strawberry Shortcake",
//     "category": "dessert",
//     "description": "Layered sponge cake with whipped cream and strawberries.",
//     "image_url": "https://images.unsplash.com/photo-1627308595171-d1b5d67129c4?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 21000,
//     "rating": 4.4,
//     "shop_name": "Sweet Spot",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 16,
//     "name": "BBQ Chicken Pizza",
//     "category": "western",
//     "description": "Pizza with BBQ chicken, red onions, and mozzarella cheese.",
//     "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=781&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 39000,
//     "rating": 4.6,
//     "shop_name": "Pizza Mania",
//     "is_promos": true,
//     "is_trending": false
//   },
//   {
//     "id": 17,
//     "name": "Cheese Fries",
//     "category": "fastfood",
//     "description": "Crispy fries topped with melted cheddar cheese.",
//     "image_url": "https://images.unsplash.com/photo-1568226189293-77924f3f10c6?q=80&w=1331&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 15000,
//     "rating": 4.0,
//     "shop_name": "Burger Bros",
//     "is_promos": false,
//     "is_trending": true
//   },
//   {
//     "id": 18,
//     "name": "Tofu Stir Fry",
//     "category": "vegan",
//     "description": "Tofu cubes stir-fried with vegetables and soy sauce.",
//     "image_url": "https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dG9mdSUyMHN0aXIlMjBmcnl8ZW58MHx8MHx8fDA%3D",
//     "price": 21000,
//     "rating": 4.2,
//     "shop_name": "Green Eats",
//     "is_promos": false,
//     "is_trending": false
//   },
//   {
//     "id": 19,
//     "name": "Chocolate Mousse",
//     "category": "dessert",
//     "description": "Rich and creamy chocolate mousse with whipped cream.",
//     "image_url": "https://images.unsplash.com/photo-1621792907526-e69888069079?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     "price": 20000,
//     "rating": 4.6,
//     "shop_name": "Sweet Spot",
//     "is_promos": true,
//     "is_trending": false
//   },
//   {
//     "id": 20,
//     "name": "Classic Carbonara",
//     "category": "western",
//     "description": "Pasta in creamy carbonara sauce with smoked beef.",
//     "image_url": "https://images.unsplash.com/photo-1560434019-4558f9a9e2a1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2FyYm9uYXJhfGVufDB8fDB8fHww",
//     "price": 32000,
//     "rating": 4.3,
//     "shop_name": "Western Delight",
//     "is_promos": false,
//     "is_trending": true
//   }
// ]
